### ISSUE TITLE
use new supported version of maknz/slack

### ISSUE THREAD

**Issue by alek13** [ariarijp/exception-to-slack-attachments#1]
Hi, @ariarijp .

package `maknz/slack` was abandoned.

please use in your package new supported version `alek13/slack` (forked from maknz).

more: https://medium.com/@alek13.me/reincarnation-of-popular-php-package-for-slack-cb2e8db98a91

**Comment by alek13** [comment]
Thanks @ariarijp for 8b77bd68ae765e6897d0187cef26e3d24a043c10

**Comment by alek13** [comment]
@ariarijp , one mistake: 
you put dependent into `"require-dev"` instead `"require"`.
https://github.com/ariarijp/exception-to-slack-attachments/commit/8b77bd68ae765e6897d0187cef26e3d24a043c10#diff-b5d0ee8c97c7abd7e3fa29b9a27d1780

**Comment by ariarijp** [comment]
@alek13 

I made a mistake previous version of this package.
This package uses Slack package for example code.

Please feel free to close or ask me.

Thanks,
Takuya

**Comment by alek13** [comment]
If so, it would be better to add this package to suggestions and not to dev.
